### ISSUE TITLE
Dependency and NPM issues

### ISSUE THREAD

**Issue by pauljlucas** [krakenjs/jwt-csrf#2]
I was seeing some dependency issues when trying to pull down from NPM (see bottom) and forked the repo just to change the package.json. Looking into the code though, the missing dependency (cryptutils-paypal) isnt even in the public github version of the code. It seems it must have been an internal module? Then after looking at the npm repo i am seeing the URL for the repo is actually your internal github (github.paypal.com). Also looking at the npm page (https://www.npmjs.com/package/jwt-csrf) the whole documentation seems to be mismatched. I would help with a PR if i could but it seems like this is just an issue with the NPM setup. If you could make sure the public repo is linked to NPM and also update the jsonwebtoken version to the latest (or atleast later than 5 to fix the big security hole from last year) that would be awesome. Not sure if the internal code is more up to date but if you also have some new things in that repo merging that to upstream / public would be very helpful as well. Looking forward to using this, and thanks for building it! 

Errors below:

```
npm WARN deprecated jsonwebtoken@4.2.2: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cryptutils-paypal
npm ERR! 404 
npm ERR! 404  'cryptutils-paypal' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'jwt-csrf'
```

**Comment by bluepnume** [comment]
Fixed! Thanks for the catch. Didn't realize doing an `npm publish` on a patch version for v3 would set the `latest` tag in npm and make that the default version, over v4.

**Comment by pauljlucas** [comment]
Perfect, thanks for the super quick fix! Just tried and NPM install worked. I would say just make sure to update the jsonwebtoken dependency to at least V5 so if someone installed this without already knowing about it (or having a higher version like i did) they would be using an old vulnerable library. I know i may take some testing though. Ill checkout how the library works with v7 and let you know if i run into any issues.
