### ISSUE TITLE
Outdated jsonwebtoken

### ISSUE THREAD

**Issue by iamdubx** [krakenjs/jwt-csrf#9]
Is it safe to use outdated jsonwebtoken@4.2.2 for such critical task?
Why not to update dependencies?

**Comment by sheminusminus** [comment]
It isn't. Version 4.2.2 of jsonwebtoken has a high-severity security vulnerability. [Snyk's analysis of jwt-csrf](https://snyk.io/test/github/krakenjs/jwt-csrf)
